"""
format_converter.py
===================
COCO JSON → YOLO txt 포맷 변환기 + data.yaml 자동 생성

🚨 레이블 인덱싱 주의
  YOLO  : 0-based  (이 모듈에서 생성하는 cat2yolo)
  Faster R-CNN / RetinaNet : 1-based  (dataset.py의 orig2model)
  둘은 동일 category_id에 대해 1 차이가 납니다.
"""

import os
import json
from collections import defaultdict
from tqdm.auto import tqdm


def convert_coco_to_yolo(json_path, output_label_dir, cat2yolo=None):
    """
    COCO JSON을 YOLO 형식의 .txt 레이블 파일로 변환합니다.

    출력 형식 (한 줄 = 객체 하나):
        <class_id> <cx> <cy> <w> <h>   (모두 0~1 정규화)

    ⚠️  train/val 일관성 주의:
        cat2yolo를 Train에서 먼저 생성한 뒤, Val 변환 시 반드시 동일한
        cat2yolo를 인자로 넘겨야 클래스 ID가 일치합니다.
        각 JSON에서 독립적으로 생성하면 소수 클래스 누락으로 인해
        train/val 간 클래스 인덱스가 어긋날 수 있습니다.

    Args:
        json_path        : COCO 형식 JSON 파일 경로
        output_label_dir : .txt 레이블 저장 폴더
        cat2yolo         : {category_id: yolo_class_id} 매핑.
                           None이면 현재 JSON에서 자동 생성 (Train 전용).

    Returns:
        cat2yolo : 사용된 클래스 매핑 딕셔너리 (Val 호출 시 재사용)
    """
    os.makedirs(output_label_dir, exist_ok=True)

    with open(json_path, 'r', encoding='utf-8') as f:
        coco = json.load(f)

    # Train 첫 실행 시에만 새로 생성, Val은 반드시 Train의 cat2yolo를 받아야 함
    if cat2yolo is None:
        all_cats = sorted(set(ann['category_id'] for ann in coco['annotations']))
        cat2yolo = {cid: i for i, cid in enumerate(all_cats)}

    id_to_img   = {img['id']: img for img in coco['images']}
    img_to_anns = defaultdict(list)
    for ann in coco['annotations']:
        img_to_anns[ann['image_id']].append(ann)

    folder_name = os.path.basename(output_label_dir)
    for img_id, anns in tqdm(img_to_anns.items(), desc=f"{folder_name} 변환"):
        img_info = id_to_img[img_id]
        W, H     = img_info['width'], img_info['height']  # 800 x 800

        txt_name = os.path.splitext(img_info['file_name'])[0] + '.txt'
        with open(os.path.join(output_label_dir, txt_name), 'w') as f:
            for ann in anns:
                x, y, w, h = ann['bbox']           # COCO: [x_min, y_min, w, h]
                cx = (x + w / 2) / W
                cy = (y + h / 2) / H
                nw = w / W
                nh = h / H
                cls = cat2yolo[ann['category_id']]
                f.write(f"{cls} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}\n")

    print(f"✅ 저장 완료 → {output_label_dir}")
    return cat2yolo


def generate_data_yaml(base_dir, cat2yolo, train_json_path, yaml_filename='data.yaml'):
    """
    Ultralytics YOLO 표준 형식의 data.yaml 파일을 자동 생성합니다.

    생성 경로: base_dir/data.yaml

    Args:
        base_dir        : 데이터셋 루트 경로 (yaml의 path 키 값)
        cat2yolo        : convert_coco_to_yolo()에서 반환된 클래스 매핑
        train_json_path : 클래스 이름 추출을 위한 train_letterbox.json 경로
        yaml_filename   : 저장할 파일명 (기본 'data.yaml')
    """
    with open(train_json_path, 'r', encoding='utf-8') as f:
        coco = json.load(f)

    id_to_name  = {cat['id']: cat['name'] for cat in coco['categories']}
    class_names = [id_to_name[cid] for cid in sorted(cat2yolo, key=cat2yolo.get)]

    yaml_content = f"""# YOLO data.yaml — Auto-generated by format_converter.py
# ✅ 이미지와 라벨(.txt)이 letterbox_images/ 안에 함께 저장됩니다.
path: {base_dir}
train: letterbox_images/train
val:   letterbox_images/val

nc: {len(class_names)}
names: {class_names}
"""
    yaml_path = os.path.join(base_dir, yaml_filename)
    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)

    print(f"✅ data.yaml 생성 완료 → {yaml_path}")
    print(f"   nc={len(class_names)}")
    return yaml_path


def run_yolo_conversion(base_dir):
    """
    train / val YOLO 레이블 변환 + data.yaml 생성을 한 번에 실행합니다.

    Args:
        base_dir : 데이터셋 루트 경로

    Example:
        from src.preprocessing.format_converter import run_yolo_conversion
        run_yolo_conversion(base_dir='/path/to/data')
    """
    train_json = os.path.join(base_dir, 'train_letterbox.json')
    val_json   = os.path.join(base_dir, 'val_letterbox.json')
    # ✅ Ultralytics YOLO는 이미지와 라벨이 같은 폴더에 있어야 합니다.
    train_lbl  = os.path.join(base_dir, 'letterbox_images/train')
    val_lbl    = os.path.join(base_dir, 'letterbox_images/val')

    print("🔄 YOLO 레이블 변환을 시작합니다...\n")
    cat2yolo = convert_coco_to_yolo(train_json, train_lbl)
    convert_coco_to_yolo(val_json, val_lbl, cat2yolo=cat2yolo)
    generate_data_yaml(base_dir, cat2yolo, train_json)
